In [8]:
# Dependencies
import pandas as pd

In [9]:
# Store filepath in a variable
file_path = "CitiesWeather.csv"

In [10]:
# Read  Data file with the pandas library
citiesweatherDF = pd.read_csv(file_path, encoding="ISO-8859-1")
citiesweatherDF

,City,Country,Latitude,Longitude,Date,Temperature,Humidity,Cloudiness,Wind Speed
0,kang,BW,-23.6752,22.7876,2021-01-14 16:29:01,30.77,33.0,69.0,2.41
1,casablanca,MA,33.5928,-7.6192,2021-01-14 16:27:33,14.51,55.0,40.0,2.06
2,huarmey,PE,-10.0681,-78.1522,2021-01-14 16:29:00,23.74,72.0,100.0,3.89
3,khatanga,RU,71.9667,102.5000,2021-01-14 16:29:03,-44.88,77.0,91.0,0.94
4,busselton,AU,-33.6500,115.3333,2021-01-14 16:29:04,15.15,73.0,35.0,0.45
...,...,...,...,...,...,...,...,...,...
577,chunhuhub,MX,19.5500,-88.6833,2021-01-14 16:35:40,22.60,83.0,98.0,1.29
578,jackson,US,42.4165,-122.8345,2021-01-14 16:35:41,3.77,93.0,90.0,0.46
579,tunceli,TR,39.1083,39.5471,2021-01-14 16:35:41,5.27,81.0,75.0,3.60
580,kangaatsiaq,GL,68.3065,-53.4641,2021-01-14 16:35:42,-8.99,96.0,100.0,1.80
581,olga,RU,43.7444,135.2892,2021-01-14 16:35:43,-13.28,81.0,97.0,2.64

In [11]:
citiesweatherDF.to_html("citiesweather.html", justify='left')